# Generated by Django 5.2.7 on 2025-10-21 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0002_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
