# Generated by Django 5.2.7 on 2025-10-30 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0004_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.JSONField(default=list)),
                ('current_turn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_turn', to='Game.player')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='Game.gameroom')),
            ],
        ),
    ]
