# Generated by Django 5.2.7 on 2025-10-30 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0005_gamemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameModel',
        ),
    ]
