# Generated by Django 5.1.1 on 2025-11-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0006_delete_gamemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='board_state',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='dice_state',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='code',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='max_players',
            field=models.IntegerField(default=4),
        ),
    ]
