# Generated by Django 5.1.1 on 2025-11-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0008_player_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
