# Generated by Django 5.1.1 on 2025-11-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0009_gameroom_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='dice_value',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
